name: crypto_app
description: Flutter Crypto Currencies trends APP. The App uses an api to fetch trends in Crypto Currencies and display them in a list order

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ">=0.11.3+12"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/2.0x/stars.png
